development:
  adapter: postgresql
  database: crowdcloud-development
  username: crowdcloud
  password: crowdcloud
  host: localhost
  encoding: utf8

production:
  adapter: postgresql
  encoding: utf8
  pool: 5