development:
  adapter: postgresql
  database: mobics-development
  username: mobics
  password: mobics
  host: localhost
  encoding: utf8

production:
  adapter: mobics
  database: mobics
  encoding: utf8
  pool: 5